from enum import Enum


class PageStatusCodes(Enum):
    INITIAL = 1
    CREATING_REPOSITORY_STARTED = 2
    CREATING_REPOSITORY_SUCCESS = 3
    CREATING_REPOSITORY_FAILURE = 4
    CREATING_PAGE_STARTED = 5
    CREATING_PAGE_SUCCESS = 6
    CREATING_PAGE_FAILURE = 7
    DEPLOYING_STARTED = 8
    DEPLOYING_SUCCESS = 9
    DEPLOYING_FAILURE = 10
